[package]
name = "rrl"
version = "0.1.0"
authors = ["am <yamukha@ukr.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[workspace]

[lib]
name = "reqresp"
path = "src/reqresp.rs"

[dependencies]
    async-trait = "0.1"
    async-std ="1.9.0"
    libp2p = " 0.38.0"
    futures = "0.3.14"
    libp2prs-runtime = {  version = "0.3.0" }
    libp2p-core = "0.28.3"
    libp2p-request-response = "0.11.0"

    libp2p-noise = "0.31.0"
    libp2p-swarm = "0.29.0"
    libp2p-yamux = "0.32.0"
    libp2p-tcp = "0.28.0"
    rust-base58  = "0.0.4"
